### ISSUE TITLE
Session synchronisation doesn't work anymore

### ISSUE THREAD

**Issue by sebChevre** [Thiht/smocker#284]
Hi from the version 0.18.3, the mecanism to synchronize sessions with env variable SMOCKER_PERSISTENCE_DIRECTORY doesn't work. This was still ok before. I try to synchronize a volume with docker. Smocker list the correct number of session, but all the elements are empty (history, mock). Therefore it's not possible too, to synchronise session with the UI. 

Thanks

**Comment by gwleclerc** [comment]
Should be fixed in 0.18.4

**Comment by ripvannwinkler** [comment]
Still does not appear to work in 0.18.4 or 0.18.5. If I reset my docker image to load 0.18.2, changing nothing else, the session mocks load as expected. Seems to be something in the newer version not loading the persistence correctly.
